[EDITED]Initial support for Skyrim Special Edition:
This is enough to get the mods tab and installers tab up and running.

Utumno: this should be equivalent to edited commit
9f74311551cc7a2a595b05a6ef2526aa5bf17e1c, added bsa constants

Added also the images from a commit by @Sharlikran otherwise:

Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 391, in main
    basher.InitLinks()
  File "bash\basher\links.py", line 728, in InitLinks
    InitStatusBar()
  File "bash\basher\links.py", line 78, in InitStatusBar
    images=imageList(u'%s%%s.png' % bush.game.fsName.lower()),
  File "bash\basher\links.py", line 54, in imageList
    return [Image(dirImages.join(template % i)) for i in (16,24,32)]
  File "bash\balt.py", line 140, in __init__
    raise ArgumentError(u"Missing resource file: %s." % self.file)
bash.bolt.ArgumentError: Missing resource file: C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\images\skyrim special edition16.png.